server:
  port: 8180

spring:
  application:
    name: produto-service
  datasource:  
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/produto
     username: produto
     password: produto
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/produto
    user: produto
    password: produto